name: new_VSL
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - pyyaml>=5.4.0
  - pip
  - pip:
    - control>=0.9.0 