# Perturbation Experiment Parameters
data:
  trace_type: 'mean' #'mean' or 'single trial'
  participant_ID: 2
  trial_ID: 1

calibration:
  fit_method: 'PySwarms Two Layer'
  tolerance: 0.001
  particle_size: 1000
  iterations: 1
  runs: 1
  null_values: 'expt config' # 'expt config', 'null', None (For parameters not used in fitting)

  #PySwarms Parameters
  c1: 0.4 #cognitive parameter
  c2: 0.8 #social parameter
  w: 0.9 #inertia weight
  k: 3 #number of neighbors for topology
  p: 2 #p-norm for distance calculation

simulation:
  duration: 10.8  # Duration of each trial in seconds
  sec_per_step: 0.005
  system_type: 'Template' # 'DIVA' or 'Template'
  ref_type: 'null'  # 'sin' or 'null'

perturbation:
  type: 'auditory'  # 'state','auditory', 'somatosensory', 'laryngeal (w/auditory masking)', 'laryngeal (w/o auditory masking)'
  magnitude: -100  # Perturbation in cents
  onset: 2.03  # Perturbation onset in seconds
  duration: 1.26  # Duration of perturbation in seconds
  ramp:
    up_duration: 0.178  # Duration of the ramp up in seconds
    down_duration: 0.250  # Duration of the ramp down in seconds

starting_params:
  arb_name: 'all'
  delays:
    actuator: 3
    sensor:
      auditory: 30
      somatosensory: 3
  system:
    A: [1]
    B: [0.8]
    C_aud: 0.4
    C_som: 1
    K_aud: 0.402553
    L_aud: 0.08929
    Kf_aud: 0.35
    K_som: 0.15153
    L_som: 0.150506 
    Kf_som: 0.35

diva_starting_params:
  kearney_name: 'D1'
  delays:
    tau_A: 22
    tau_S: 31
    tau_As: 2
    tau_Ss: 3
  gains:
    alpha_A: 0.010
    alpha_S: 0.013
    alpha_As: 0.4
    alpha_Ss: 1
    alpha_Av: 0.4
    alpha_Sv: 1

  # delays:

  #   actuator: 2

  #   sensor:


  #     auditory: 3  Add commentMore actions


  #     auditory: 20

  #     somatosensory: 3

  # system:


  #   A: [0.5]


  #   B: [1]


  #   C_aud: [1]


  #   A: [0.8]


  #   B: [1.1]


  #   C_aud: [0.4]

  #   C_som: [1]


  #   K_aud: 0.2655


  #   L_aud: 0.2655  


  #   K_som: 0.2655


  #   L_som: 0.2655  


  #   K_aud: 0.20


  #   L_aud: 0.30


  #   Kf_aud: 0.35


  #   K_som: 0.36002242


  #   L_som: 0.40707844  


  #   Kf_som: 0.35
