# Perturbation Experiment Parameters
data:
  trace_type: 'mean' #'mean' or 'single trial'
  participant_ID: 2
  trial_ID: 1

simulation:
  duration: 10.8  # Duration of each trial in seconds
  sec_per_step: 0.01
  ref_type: 'null'  # 'sin' or 'null'

perturbation:
  type: 'auditory'  # 'state','auditory', 'somatosensory', 'laryngeal (w/auditory masking)', 'laryngeal (w/o auditory masking)'
  magnitude: -100  # Perturbation in cents
  onset: 2.03  # Perturbation onset in seconds
  duration: 1.26  # Duration of perturbation in seconds
  ramp:
    up_duration: 0.178  # Duration of the ramp up in seconds
    down_duration: 0.250  # Duration of the ramp down in seconds

starting_params:
  delays:
    actuator: 2
    sensor:
      auditory: 19
      somatosensory: 3
  system:
    A: [0.75699891]
    B: [1.09588468]
    C_aud: [0.40372519]
    C_som: [1]
    K_aud: 0.17743609531542626
    L_aud: 0.27839281839073576
    Kf_aud: 0.35
    K_som: 0.36002242
    L_som: 0.40707844  
    Kf_som: 0.35


# Optimized parameters:
# A: [0.75699891]
# B: [1.09588468]
# C_aud: [0.40372519]
# C_som: [1.]
# K_aud: 0.17743609531542626
# L_aud: 0.27839281839073576
# K_som: 0.36002242
# L_som: 0.40707844
# sensor_delay_aud: 19
# sensor_delay_som: 3
# actuator_delay: 2