# File paths configuration
paths:
  base_dir: 
  interp_folder: 'Interp_Data'
  fig_save_path: 
  data_save_path: 
  calibration_data:
    directory:
    mean_aud_filename: 'secs_Smith-et-al-2020-auditory-perturbation-baseline-normalized.csv'
    unprocessed_indiv_files:
      base_study_name: 'Smith-et-al-2020'
      auditory:
        path: 
        basename: 'Smith-et-al-2020-auditory-perturbation-baseline-normalized-DRF'
      laryngeal:
        path: 
        basename: 'Smith-et-al-2020-laryngeal-perturbation-no-masking-baseline-normalized'
    processed_indiv_files:
      base_study_name: 'Smith-et-al-2020'
      auditory:
        path: 
        basename: 'secs_Smith-et-al-2020-auditory-perturbation-baseline-normalized-DRF'
      laryngeal:
        path:
        basename: 'secs_Smith-et-al-2020-laryngeal-perturbation-no-masking-baseline-normalized'
